---
label: Services
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: true
  default: ''
  config:
    required: false
- name: layout
  label: Layout
  type: text
  hidden: true
  default: ''
- name: mini_desc
  label: Mini desc
  type: textarea
  hidden: false
  default: ''
  config:
    required: true
- type: textarea
  name: activities
  label: Activités
  config:
    required: true
  description: Listes des activités comprises
- type: file
  name: image
  label: Image
  hidden: false
  description: Image principale
- type: file
  name: logo
  label: Logo
  description: Seconde image
pages:
- _services/tapis-valise.md
- _services/vitres.md
- _services/interieur-exterieur.md
- _services/shampooing-moteur-interieur.md
- _services/moto.md
- _services/remise-a-neuf.md
- _services/services-aux-entreprises.md
- _services/phares.md
